#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for executor
#
# IDENTIFICATION
#    src/backend/executor/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/kde_feedback
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

OBJS = kde_feedback.o

include $(top_srcdir)/src/backend/common.mk
