#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for optimizer/path/gpukde/lbfgs
#
# IDENTIFICATION
#    src/backend/optimizer/path/gpukde/lbfgs/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/optimizer/path/gpukde/lbfgs
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

OBJS = lbfgs.o

include $(top_srcdir)/src/backend/common.mk