#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for optimizer/path/gpukde/container
#
# IDENTIFICATION
#    src/backend/optimizer/path/gpukde/container/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/optimizer/path/gpukde/container
top_builddir = ../../../../../..
include $(top_builddir)/src/Makefile.global

OBJS = directory.o dictionary.o

include $(top_srcdir)/src/backend/common.mk